"""Role 1b -- the rail-agnostic cryptographic hard gate: threshold signatures.

Role 1 (`xrpl_cosigner`) makes the enforcer a mandatory co-signer on *one* XRPL
account. This is its generalization. The funding key is a single public key whose
secret is split into shares (here a 2-of-2 additive split: agent + enforcer). No
single shareholder can produce a signature that verifies against the aggregate
key -- the enforcer's share is mixed into *every* signature or there is no valid
signature at all. So the enforcer becomes a mandatory co-signer for every chain
at once, on any rail that accepts a plain signature (an EVM EOA, a stablecoin
transfer, a custodial API keyed to one pubkey), without per-ledger SignerList
setup. The kernel is untouched: like every authorizer, this one refuses to
contribute its share unless `verifier.verify_token` passes and the proposed
transaction is bound to *this* approved Cart.

What this is, precisely
-----------------------
A genuine 2-of-2 threshold Schnorr signature over edwards25519, computed with
libsodium's group primitives (via PyNaCl). Key shares add: ``X = X_agent +
X_enforcer``. Signing is the standard two-round Schnorr with a joint nonce
``R = R_agent + R_enforcer`` and per-party partials ``s_i = r_i + c * x_i`` where
``c = H(R, X, m)``; the combined ``s = s_agent + s_enforcer`` verifies as a
single Schnorr signature ``(R, s)`` under the aggregate key ``X``. Neither party's
partial verifies against ``X`` on its own -- that is the whole property, and the
attack test (`test_role1b_threshold_requires_enforcer_share`) proves it.

PoC honesty (the swap seam, mirroring crypto.py / canonical.py)
---------------------------------------------------------------
* This is a *self-contained* threshold Schnorr verified by `group_verify`, not a
  drop-in for a stock Ed25519 verifier: stock Ed25519 fixes the nonce derivation
  and key clamping, which an interactive threshold protocol cannot reproduce.
  Production would use **FROST(ed25519)** so the combined signature verifies
  under an off-the-shelf Ed25519 verifier, and an MPC nonce-commitment round
  (each party commits to a hash of ``R_i`` before revealing it) to close the
  adaptive-nonce gap. The split is isolated here exactly as `crypto.sign/verify`
  isolates the curve choice.
* 2-of-2 additive sharing keeps the math legible. A real t-of-n threshold adds
  Lagrange coefficients at combination time; the gate and binding logic below are
  identical regardless of (t, n).
"""
from __future__ import annotations

import os
from dataclasses import dataclass
from hashlib import sha512
from typing import List, Optional, Tuple

import nacl.bindings as _b

from .base import AuthorizationResult, Authorizer
from ..canonical import canonical_json
from ..models import ExecutionRequest, ExecutionToken

# -- edwards25519 group primitives (scalars and points are 32-byte values) --

_base = _b.crypto_scalarmult_ed25519_base_noclamp          # scalar -> scalar*G
_scalarmult = _b.crypto_scalarmult_ed25519_noclamp         # (scalar, point) -> scalar*P
_point_add = _b.crypto_core_ed25519_add                    # P + Q
_scalar_add = _b.crypto_core_ed25519_scalar_add            # (a + b) mod L
_scalar_mul = _b.crypto_core_ed25519_scalar_mul            # (a * b) mod L
_scalar_reduce = _b.crypto_core_ed25519_scalar_reduce      # 64 bytes -> scalar mod L


def _rand_scalar() -> bytes:
    """A uniform scalar mod L (the curve order)."""
    return _scalar_reduce(os.urandom(64))


def challenge(R: bytes, group_pubkey: bytes, message: bytes) -> bytes:
    """Schnorr challenge c = H(R || X || m) reduced mod L."""
    return _scalar_reduce(sha512(R + group_pubkey + message).digest())


# -- key setup --

@dataclass
class ThresholdGroup:
    """A 2-of-2 additive split of one funding key.

    ``agent_share`` / ``enforcer_share`` are secret scalars; ``pubkey`` is the
    aggregate public point both shares jointly control. Only the agent ever holds
    ``agent_share``; only the cosigner ever holds ``enforcer_share``.
    """
    agent_share: bytes
    enforcer_share: bytes
    pubkey: bytes


def setup_2of2() -> ThresholdGroup:
    """Deal a fresh 2-of-2 split. (In production the shares are generated by a
    distributed key-generation ceremony so the full key never exists anywhere.)"""
    x_agent = _rand_scalar()
    x_enforcer = _rand_scalar()
    pubkey = _point_add(_base(x_agent), _base(x_enforcer))
    return ThresholdGroup(agent_share=x_agent,
                          enforcer_share=x_enforcer,
                          pubkey=pubkey)


# -- the transaction being signed --

@dataclass
class ThresholdTx:
    """The exact action the threshold signature commits to. Binding the
    destination and amount into the signed message means a redirected or
    re-priced payment is a *different* message -- a signature for one does not
    settle the other, independent of the enforcer's own context check."""
    chain_hash: str
    destination: str
    amount: int
    currency: str
    rail: str = "mpc"

    def message(self) -> bytes:
        return canonical_json({
            "chain_hash": self.chain_hash,
            "destination": self.destination,
            "amount": self.amount,
            "currency": self.currency,
            "rail": self.rail,
        })


# -- party operations (used by the agent; the enforcer reuses them internally) --

def agent_commit() -> Tuple[bytes, bytes]:
    """Round 1: pick a nonce r and publish its commitment R = r*G."""
    r = _rand_scalar()
    return r, _base(r)


def agent_partial(nonce: bytes, share: bytes, c: bytes) -> bytes:
    """Round 2: partial signature s_i = r_i + c * x_i (mod L)."""
    return _scalar_add(nonce, _scalar_mul(c, share))


def combine_scalars(partials: List[bytes]) -> bytes:
    """Sum partial signatures into the combined Schnorr scalar s."""
    total = partials[0]
    for p in partials[1:]:
        total = _scalar_add(total, p)
    return total


def group_verify(group_pubkey: bytes, message: bytes, R: bytes, s: bytes) -> bool:
    """Standard Schnorr check: s*G == R + c*X. True only for a signature that
    carries every shareholder's contribution."""
    try:
        c = challenge(R, group_pubkey, message)
        lhs = _base(s)                                  # s*G
        rhs = _point_add(R, _scalarmult(c, group_pubkey))  # R + c*X
        return lhs == rhs
    except Exception:
        return False


@dataclass
class EnforcerContribution:
    """The enforcer's released share of one signature: the joint nonce R, the
    challenge c it was computed under, and the enforcer partial s_e. The agent
    finalizes with its own partial: ``s = combine_scalars([s_agent, s_e])``."""
    R: bytes
    c: bytes
    s_e: bytes


# -- the authorizer --

class MPCThresholdCosigner(Authorizer):
    rail = "mpc"

    def __init__(self, verifier, enforcer_verify_key: str,
                 enforcer_share: bytes, group_pubkey: bytes):
        self._verifier = verifier
        self._enforcer_vk = enforcer_verify_key
        self._share = enforcer_share        # the share the agent never holds
        self.group_pubkey = group_pubkey

    def cosign(self, tx: ThresholdTx, agent_commitment: bytes,
               token: ExecutionToken,
               req: ExecutionRequest) -> Tuple[Optional[EnforcerContribution], str]:
        """Release the enforcer's signature share ONLY for a valid, approved,
        exactly-matching transaction. Mirrors `xrpl_cosigner.cosign`: trust the
        enforcer token (never the agent's word), then re-bind the on-rail action
        to the approved Cart context before contributing anything."""
        if not self._verifier.verify_token(token, self._enforcer_vk):
            return None, "Enforcer token invalid/expired -- refusing to contribute share."
        # Bind to the approved AP2 context (no redirection / re-pricing).
        if tx.destination != req.context.destination_account:
            return None, "Threshold destination does not match approved Cart -- refusing to contribute share."
        if tx.amount != req.context.amount:
            return None, "Threshold amount does not match approved Cart -- refusing to contribute share."
        if tx.currency != req.context.currency:
            return None, "Threshold currency does not match approved Cart -- refusing to contribute share."

        # Round 2: joint nonce, challenge over the aggregate key, enforcer partial.
        r_e, R_e = agent_commit()
        R = _point_add(agent_commitment, R_e)
        c = challenge(R, self.group_pubkey, tx.message())
        s_e = agent_partial(r_e, self._share, c)
        return EnforcerContribution(R=R, c=c, s_e=s_e), \
            "Enforcer contributed share; group signature reachable."

    def authorize(self, token: ExecutionToken,
                  req: ExecutionRequest) -> AuthorizationResult:
        # Producing a signature needs the agent's secret share, which this enforcer-side authorizer
        # deliberately does not hold (neither side can sign alone). This rail OVERRIDES the base
        # template; its real entry is the interactive cosign path. Bringing cosign under an
        # analogous template is a separate, flagged pass (same convention gap, by design).
        raise NotImplementedError(
            "Use agent_commit/cosign/combine_scalars explicitly, or the demo helper."
        )

    # The base ABC now declares these hooks; the cosign path does not use the single-arg template,
    # so they are stubs that point at `cosign`. (Implemented only to keep the class instantiable.)
    def recheck_against_context(self, token, req):
        raise NotImplementedError("MPC uses the interactive agent_commit/cosign/combine path.")

    def produce_capability(self, token, req):
        raise NotImplementedError("MPC uses the interactive agent_commit/cosign/combine path.")
