"""GENERATED by /signet-onboard — guarded-browser demo for Acme Shop (generic store, illustrative).

`python -m examples.browser_demo.run_acmeshop`

Reuses the ENTIRE Spec 02-06 run loop (live steering, panels, voice, task steer, the path
dual-check) via `run_interactive.RunConfig` — only the mandate, task, allow-list, and scope goals
change. The kernel and the gate are untouched; this file is pure configuration.

THE WALL: the ceiling deliberately omits `/order-complete` — placing the order, the one
irreversible step — so no scope and no operator (and no prompt-injected goal) can ever reach it.
Every other lane is a declared subset of the ceiling; the gate dual-checks ceiling AND active
scope on every decision.

NOTE (illustrative): `shop.example.com` is the docs-reserved domain — this demo exists to prove the
generator and the offline structural arc. Its `/products`, `/cart`, `/checkout` paths are
conventional ASSUMPTIONS; verify the real paths against the live site before presenting.
"""
from __future__ import annotations

import asyncio
import os

from . import run_interactive
from .web_mandate import WebMandate

START_URL = "https://shop.example.com/"

# URL PATHS (rooted at '/', fnmatch globs; query strings are dropped before matching, so glob the
# path only — `/products*` already covers `/products?id=4` and `/product.html?id=4`).
_CEILING_PATHS  = ["/", "/products*", "/cart", "/checkout"]   # THE WALL — no /order-complete
_BROWSE_PATHS   = ["/", "/products*", "/cart"]                # browse + read the cart
_SHOP_PATHS     = ["/", "/products*", "/cart"]                # add/remove, view cart
_CHECKOUT_PATHS = ["/", "/products*", "/cart", "/checkout"]   # + the shipping form


def build_mandate() -> "WebMandate":
    return (
        WebMandate("demo-agent", task_id="acmeshop-001")
        # CEILING — the maximum authority that can ever apply. The wall: it omits /order-complete.
        .ceiling(domains=["example.com"], actions=["navigate", "click", "type", "extract"],
                 path_allow=_CEILING_PATHS)
        # BROWSE — read-only: navigate + extract; can browse + read the cart, cannot click/type.
        .scope("browse",   domains=["example.com"], actions=["navigate", "extract"],
               click_policy="in_domain_only", path_allow=_BROWSE_PATHS)
        # SHOP (default) — full interaction; checkout path is out of the lane.
        .scope("shop",     domains=["example.com"], actions=["navigate", "click", "type", "extract"],
               click_policy="allow_unresolved", path_allow=_SHOP_PATHS)
        # CHECKOUT — the shipping form; still cannot place the order (ceiling wall).
        .scope("checkout", domains=["example.com"], actions=["navigate", "click", "type", "extract"],
               click_policy="allow_unresolved", path_allow=_CHECKOUT_PATHS)
        .default_scope("shop")   # default must let the first steps happen (browse + add to cart)
        .build()
    )


TASK = (
    "You are a shopping assistant on Acme Shop, taking LIVE direction from a human operator. Use "
    f"`navigate` to open {START_URL} and `extract` to read the catalog. FOLLOW THE OPERATOR'S ITEM "
    "INSTRUCTIONS: when told to ADD an item (e.g. 'add the blue mug'), `click` that product's 'Add "
    "to cart' control; when told to REMOVE one, `click` its 'Remove' control — on the catalog or "
    "inside the cart. You can `click` the cart to open /cart and `extract` to read its contents. Do "
    "NOT proceed to checkout on your own — only when the operator tells you to; then on /checkout "
    "`type` a name, address, and zip. IMPORTANT: if any action is BLOCKED, do NOT give up — report "
    "exactly what was blocked and why, then retry the SAME action on a later step (the operator may "
    "change the active scope between your steps). NEVER attempt to place/confirm the order "
    "(/order-complete) — it is outside your authority. When the operator says you are finished, "
    "`extract` the cart, report it, and call `done`."
)

# browser-use's own belt — a SUPERSET of the gate's ceiling domains (the gate is enforcer of
# record, but if a ceiling domain is missing here the PAGE NEVER LOADS and the gate never decides).
BROWSER_ALLOWED_DOMAINS = ["*.example.com", "https://*.example.com"]

# When the operator steers INTO a lane, also tell the agent to USE it (a scope switch changes
# AUTHORITY but is silent to the agent — without this it sits re-reading the page).
_SCOPE_GOALS = {
    "checkout": ("The operator has opened the CHECKOUT lane. First SHOW THE CART: open /cart and "
                 "`extract` to report what's in it. Then go to /checkout and `type` a name, "
                 "address, and zip. Do NOT place or confirm the order (/order-complete is outside "
                 "your authority)."),
    "shop":     ("The operator is back in the SHOP lane. Return to the catalog (/products) and "
                 "continue adding or removing items as directed."),
}


def config() -> "run_interactive.RunConfig":
    return run_interactive.RunConfig(
        build_mandate=build_mandate, task=TASK, allowed_domains=BROWSER_ALLOWED_DOMAINS,
        start_url=START_URL, session_id="acmeshop-paths-demo",
        title="path-scoped WebMandate (acmeshop)", scope_goals=_SCOPE_GOALS)


def main() -> int:
    # Item shopping IS this demo, so default task steering ON (so "add the blue mug" works without a
    # flag). Set SIGNET_TASK_STEER=0 to turn item steering off and keep only lane steering.
    os.environ.setdefault("SIGNET_TASK_STEER", "1")
    return asyncio.run(run_interactive._run(config()))


if __name__ == "__main__":
    raise SystemExit(main())
