"""GENERATED by /signet-onboard — OFFLINE proof for Acme Shop (no LLM, no browser, no network).

`python -m examples.browser_demo.selfcheck_acmeshop`

Proves the structural claims the demo makes, deterministically, so the live arc (which needs DNS
this sandbox may not serve) only has to be eyeballed. Exits non-zero on any failed assertion.
"""
from __future__ import annotations

from .gate import decide
from .run_acmeshop import build_mandate


def _allow(m, action, target, **kw):
    d = decide(m, action, target, **kw)
    assert d.allowed, f"expected ALLOW for {action} {target} under {m.active!r}: {d.reason}"
    return d


def _block(m, action, target, needle="", **kw):
    d = decide(m, action, target, **kw)
    assert not d.allowed, f"expected BLOCK for {action} {target} under {m.active!r}: {d.reason}"
    if needle:
        assert needle in d.reason, f"expected {needle!r} in reason, got: {d.reason}"
    return d


def main() -> int:
    m = build_mandate()
    assert isinstance(m.menu, dict) and m.menu, "mandate must build a non-empty menu"
    assert m.active == "shop", f"default lane should be 'shop', got {m.active!r}"
    print(f"[selfcheck] lanes={list(m.menu)}  default={m.active!r}  "
          f"ceiling_domains={sorted(m.ceiling.allowed_domains)}")

    # --- THE WALL: /order-complete is outside the ceiling under EVERY lane (ceiling-deny) ---------
    for lane in m.menu:
        m.active = lane
        _block(m, "navigate", "https://shop.example.com/order-complete", needle="ceiling")
    print("[selfcheck] wall holds: /order-complete blocked under every lane (ceiling-deny)")

    # --- operate lane works on the landing + working area -----------------------------------------
    m.active = "shop"
    _allow(m, "navigate", "https://shop.example.com/")
    _allow(m, "navigate", "https://shop.example.com/products?id=4")
    _allow(m, "extract",  "https://shop.example.com/cart")
    print("[selfcheck] shop: landing + /products + /cart allowed")

    # --- read-only lane is action-gated: it can read but not click/type ---------------------------
    m.active = "browse"
    _allow(m, "extract", "https://shop.example.com/products")
    _block(m, "click", "https://shop.example.com/products", needle="not in scope")
    _block(m, "type",  "https://shop.example.com/products", needle="not in scope")
    print("[selfcheck] browse: read-only (click/type denied by action)")

    # --- /checkout is PATH-gated: scope-deny under shop, ALLOW after steering up to checkout -------
    m.active = "shop"
    _block(m, "navigate", "https://shop.example.com/checkout", needle="not in scope")
    m.active = "checkout"
    _allow(m, "navigate", "https://shop.example.com/checkout")
    # ...but even checkout cannot cross the wall:
    _block(m, "navigate", "https://shop.example.com/order-complete", needle="ceiling")
    print("[selfcheck] /checkout: scope-deny under shop, allowed under checkout; wall still holds")

    print("[selfcheck] PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
