"""Shape a `signet attack-me --json` run into the trace dict the demo template consumes.

Generated-by-construction, exactly like demos/build_demo.py for the kernel gauntlet: this
runs the REAL local gate (`signet attack-me --json`) in a throwaway sandbox at build time
and projects its structured output into the "Local gate — attack me" tab. No verdict here
is authored; every one is read back out of the gate's own signed receipt.

The absolute tmp sandbox path is deliberately NOT carried into the published page (it is
ephemeral and machine-specific). The page shows the reproducible command instead.

Run:  python -m demos.build_attack_trace        # prints the shaped trace as JSON
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Narration grouping for the three escalating acts (mirrors the CLI's ACT_GROUPS).
_GROUP = {
    "1": "ACT 1 · touch a protected file",
    "2a": "ACT 2 · disable the gate itself",
    "2b": "ACT 2 · disable the gate itself",
    "3a": "ACT 3 · push to a protected branch",
    "3b": "ACT 3 · push to a protected branch",
}


def _payload_str(act: dict) -> str:
    ti = act["payload"]["tool_input"]
    if act["tool"] == "Bash":
        return ti.get("command", "")
    return ti.get("file_path", "")


def build_attack_trace() -> dict:
    """Run the shipped `signet attack-me --json` and reshape for the web tab."""
    out = subprocess.run(
        [sys.executable, "-m", "signet.cli.main", "attack-me", "--json"],
        cwd=str(ROOT), capture_output=True, text=True, timeout=180)
    if out.returncode not in (0, 3):   # 3 = an act missed its expectation (still truthful data)
        raise RuntimeError(f"attack-me failed (rc={out.returncode}): {out.stderr}")
    raw = json.loads(out.stdout)

    acts = []
    for a in raw["acts"]:
        acts.append({
            "group": _GROUP.get(a["n"], a["n"]),
            "n": a["n"], "title": a["title"], "narration": a["narration"],
            "tool": a["tool"], "payload_str": _payload_str(a),
            "verdict": a["verdict"], "cause": a["cause"],
            # The published page carries a STABLE "signed" marker, not the per-run uuid
            # receipt id: that id belongs to an ephemeral sandbox deleted on exit, so it is
            # unverifiable by a page viewer and would churn docs/ on every build. The real
            # ids live in `attack-me --json` / `--keep` for self-verification.
            "receipt": "signed ✓" if a["receipt_id"] else "—",
            "expected": a["expected"], "passed": a["passed"],
            "honest_note": a["honest_note"],
        })

    return {
        "label": "signet attack-me — the local PreToolUse gate",
        "eyebrow_kind": "real local gate, run at build time",
        "subtitle": ("A hijacked agent attacks a fenced repo; every verdict was produced by "
                     "the shipped Stage 1 gate and read back out of a signed receipt."),
        "acts": acts,
        "receipt_count": sum(1 for a in raw["acts"] if a["receipt_id"]),
        "all_passed": raw["all_passed"],
        "verify_hint": "signet attack-me --keep && signet receipts --verify",
        "provenance": ("Generated by running `signet attack-me --json` against a throwaway git "
                       "sandbox fenced by the real `signet init` default policy. The bash "
                       "command in ACT 3 is string-matched only — never executed."),
        "boundary": raw["boundary"],
    }


if __name__ == "__main__":
    print(json.dumps(build_attack_trace(), indent=2))
